-- Wallust colorscheme integration
-- Uses native Lua colorscheme generated by wallust template

return {
  -- Simple plugin spec to load wallust colorscheme
  {
    "wallust-colorscheme",
    dir = vim.fn.stdpath("config") .. "/colors",
    lazy = false,
    priority = 1000,
    config = function()
      -- Load wallust colorscheme
      vim.cmd.colorscheme("wallust")

      -- Trouble v3 highlight fixes
      vim.api.nvim_set_hl(0, "TroubleNormal", { link = "Normal" })
      vim.api.nvim_set_hl(0, "TroubleText", { link = "Normal" })
      vim.api.nvim_set_hl(0, "TroubleCount", { link = "TabLineSel" })
      vim.api.nvim_set_hl(0, "TroubleDirectory", { link = "Directory" })
      vim.api.nvim_set_hl(0, "TroubleFileName", { link = "Directory" })
    end,
  },
}
